from node import Node
from binary import BinaryTree

def main():
    print("Creating root and tree...")
    root = Node(50, 2)
    tree = BinaryTree(root)
    print("Done.")
    tree.display(root)
    print()
    
    print("Adding 25 to the tree:")
    tree.add(root, 25)
    tree.display(root)
    print()
    print("Adding 25 to the tree:")
    tree.add(root, 25)
    tree.display(root)
    print()
    print("Adding 75 to the tree:")
    tree.add(root, 75)
    tree.display(root)
    print()
    print("Adding 100 to the tree:")
    tree.add(root, 100)
    tree.display(root)
    print()
    print("Adding 0 to the tree:")
    tree.add(root, 0)
    tree.display(root)
    print()
    print("Adding 65 to the tree:")
    tree.add(root, 65)
    tree.display(root)
    print()
    print("Adding 33 to the tree:")
    tree.add(root, 33)
    tree.display(root)
    print()
    print("Adding 45 to the tree:")
    tree.add(root, 45)
    tree.display(root)
    print()
    print("Adding 55 to the tree:")
    tree.add(root, 55)
    tree.display(root)
    print()
    print("Adding 10 to the tree:")
    tree.add(root, 10)
    tree.display(root)
    print()
    print("Adding 12 to the tree:")
    tree.add(root, 12)
    tree.display(root)
    print()
    print("The tree has {} levels.".format(tree.levels(root)))

if __name__ == "__main__":
    main()